# Generated by Django 2.1.5 on 2020-02-22 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='adventure games', max_length=255)),
                ('rate', models.FloatField(default=4)),
                ('review', models.CharField(max_length=3000)),
                ('image_url', models.CharField(default='https://www.google.co.in/imghp?hl=en', max_length=2083)),
                ('download_url', models.CharField(default='https://play.google.com/store?utm_source=apac_Med&utm_medium=hasem&utm_content=Jan0220&utm_campaign=Evergreen&pcampaignid=MKT-DR-apac-in-1003227-Med-hasem-py-Evergreen-Jan0220-Text_Search_BKWS-BKWS%7cONSEM_kwid_43700012164778770_creativeid_113397194705_device_c_kwd_kwd-41905086_geoid_9061998_network_g&gclid=Cj0KCQiA-bjyBRCcARIsAFboWg1PUNWG7Ag2lqbOAMNLdf- _-8G-gBIpwsWChOTKUSnPylgf691vwP4aAkhgEALw_wcB&gclsrc=aw.ds', max_length=2083)),
            ],
        ),
    ]
