# Generated by Django 2.1.5 on 2020-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmrcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games1',
            name='name',
            field=models.CharField(default='write name here', max_length=255),
        ),
        migrations.AddField(
            model_name='games1',
            name='rate',
            field=models.FloatField(default=4),
        ),
    ]
