# Generated by Django 2.1.5 on 2020-02-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmrcm', '0002_auto_20200220_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='action games', max_length=255)),
                ('rate', models.FloatField(default=4)),
                ('review', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Games3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='strategy games', max_length=255)),
                ('rate', models.FloatField(default=4)),
                ('review', models.CharField(max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='games1',
            name='name',
            field=models.CharField(default='adventure games', max_length=255),
        ),
    ]
