# Generated by Django 2.1.5 on 2020-02-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmrcm', '0003_auto_20200221_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='games1',
            name='download_url',
            field=models.CharField(default='https://play.google.com/store?utm_source=apac_Med&utm_medium=hasem&utm_content=Jan0220&utm_campaign=Evergreen&pcampaignid=MKT-DR-apac-in-1003227-Med-hasem-py-Evergreen-Jan0220-Text_Search_BKWS-BKWS%7cONSEM_kwid_43700012164778770_creativeid_113397194705_device_c_kwd_kwd-41905086_geoid_9061998_network_g&gclid=Cj0KCQiA-bjyBRCcARIsAFboWg1PUNWG7Ag2lqbOAMNLdf- _-8G-gBIpwsWChOTKUSnPylgf691vwP4aAkhgEALw_wcB&gclsrc=aw.ds', max_length=2083),
        ),
        migrations.AddField(
            model_name='games1',
            name='image_url',
            field=models.CharField(default='https://www.google.co.in/imghp?hl=en', max_length=2083),
        ),
        migrations.AddField(
            model_name='games2',
            name='download_url',
            field=models.CharField(default='https://play.google.com/store?utm_source=apac_Med&utm_medium=hasem&utm_content=Jan0220&utm_campaign=Evergreen&pcampaignid=MKT-DR-apac-in-1003227-Med-hasem-py-Evergreen-Jan0220-Text_Search_BKWS-BKWS%7cONSEM_kwid_43700012164778770_creativeid_113397194705_device_c_kwd_kwd-41905086_geoid_9061998_network_g&gclid=Cj0KCQiA-bjyBRCcARIsAFboWg1PUNWG7Ag2lqbOAMNLdf- _-8G-gBIpwsWChOTKUSnPylgf691vwP4aAkhgEALw_wcB&gclsrc=aw.ds', max_length=2083),
        ),
        migrations.AddField(
            model_name='games2',
            name='image_url',
            field=models.CharField(default='https://www.google.co.in/imghp?hl=en', max_length=2083),
        ),
        migrations.AddField(
            model_name='games3',
            name='download_url',
            field=models.CharField(default='https://play.google.com/store?utm_source=apac_Med&utm_medium=hasem&utm_content=Jan0220&utm_campaign=Evergreen&pcampaignid=MKT-DR-apac-in-1003227-Med-hasem-py-Evergreen-Jan0220-Text_Search_BKWS-BKWS%7cONSEM_kwid_43700012164778770_creativeid_113397194705_device_c_kwd_kwd-41905086_geoid_9061998_network_g&gclid=Cj0KCQiA-bjyBRCcARIsAFboWg1PUNWG7Ag2lqbOAMNLdf- _-8G-gBIpwsWChOTKUSnPylgf691vwP4aAkhgEALw_wcB&gclsrc=aw.ds', max_length=2083),
        ),
        migrations.AddField(
            model_name='games3',
            name='image_url',
            field=models.CharField(default='https://www.google.co.in/imghp?hl=en', max_length=2083),
        ),
    ]
